Error that adb not installed if `adb devices` has NotFound error (#110)
The base OS error text is confusing as to wait is missing:

Error: No such file or directory (os error 2)

Replace with an error with more context:

Cannot list devices because adb is not installed